spring:
  application:
    name: QMessagerBackend
  security:
    jwt:
      key: abc-def
      expire: 7
  datasource:
    url: jdbc:mysql://qbychat-global.mysql.polardb.rds.aliyuncs.com:3306/qbychat
    username: proc
    password: qbychatproc114514%
    driver-class-name: com.mysql.cj.jdbc.Driver