spring:
  application:
    name: QMessagerBackend
  security:
    jwt:
      key: abc-def
      expire: 7
  datasource:
    url: jdbc:mysql://qbychat-global.mysql.polardb.rds.aliyuncs.com:3306/qbychat
    username: proc
    password: qbychatproc114514%
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Mail config moved to MailConfig.
#server:
#  ssl:
#    certificate: "classpath:public.crt"
#    certificate-private-key: "classpath:private.key"
#    trust-certificate: "classpath:public.crt"
messenger:
  verify:
    email-verify-url: http://localhost:8080/user/apply-register?uuid=