spring:
  application:
    name: QMessagerBackend
  security:
    jwt:
      key: abc-def
      expire: 7
  datasource:
    url: jdbc:mysql://qbychat-global.mysql.polardb.rds.aliyuncs.com:3306/qbychat
    username: proc
    password: qbychatproc114514%
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp-mail.outlook.com
    protocol: smtp
    default-encoding: UTF-8
    username: zxysb1145@outlook.com
    password: qwer1145
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
