spring:
  application:
    name: QMessagerBackend
  security:
    jwt:
      key: abc-def
      expire: 7
  datasource:
    url: jdbc:mysql://qbychat-global.mysql.polardb.rds.aliyuncs.com:3306/qbychat
    username: proc
    password: qbychatproc114514%
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: zxysb
    password: qwer1145
    host: smtp-mail.outlook.com
    port: 587
    properties:
      mail:
        smtp:
#          ssl:
#            enable: true
#            socketFactory:
#              class: com.sun.mail.util.MailSSLSocketFactory
#              fallback: false
          auth: true
        starttls:
          enable: true
          required: true
    test-connection: true

messenger:
  verify:
    email-verify-url: http://localhost:8080/user/apply-register?uuid=
  message:
    # Key length MUST equal 16
    secret-key: powered-by-zzyss
    page:
      size: 100
  registration:
    allow: false
    invitation:
      expire: 7